services:
  comfy:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 9778:8188
    runtime: nvidia
    container_name: comfy
    isolation: process
    networks:
      - comfy-net
    volumes:
      - 'D:\comfy\models:C:\app\ComfyUI\models'
      - comfy_output:C:\app\ComfyUI\output
      - custom_nodes:C:\app\custom_nodes
    devices:
      - class/5B45201D-F2F2-4F3B-85BB-30FF1F953599

  image_server:
    build:
      context: .
      dockerfile: Dockerfile.server
    restart: always
    ports:
      - "9779:5000"
    volumes:
      - comfy_output:/images
    networks:
      - comfy-net
    depends_on:
      - comfy

  cloudflared:
    build:
      context: .
      dockerfile: Dockerfile.cloudflared
    restart: always
    networks:
      - comfy-net
    environment:
      # This token will be read from the .env file
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - comfy
      - image_server # Wait for both services to be available

networks:
  comfy-net:
    name: comfy-net
    external: true

volumes:
  custom_nodes: {}
  comfy_output: {}
