services:
  comfy:
    build: .
    restart: always
    runtime: nvidia
    container_name: comfy
    isolation: process
    networks:
      - comfy-net
    volumes:
      - 'D:\comfy\models:C:\app\ComfyUI\models'
      - 'D:\comfy\output:C:\app\ComfyUI\output'
      - custom_nodes:C:\app\base_custom_nodes
    devices:
      - class/5B45201D-F2F2-4F3B-85BB-30FF1F953599

networks:
  comfy-net:
    name: comfy-net

volumes:
  custom_nodes:
